nodes:
  - memory: 512
    ip: 127.0.0.1
    imagepath: "/tmp/"

images:
  openwrt: /home/kamil/openwrt-x86-generic-combined-ext2.img
  
vms:
  small:
    memory: 32
  medium:
    memory: 48
  large:
    memory: 64